Fix wrong dart-sdk directory name

diff --git a/wercker-box.yml b/wercker-box.yml
--- a/wercker-box.yml
+++ b/wercker-box.yml
@@ -5,17 +5,15 @@ type: main
 platform: ubuntu@12.04
 description: "A box create to build, test and deploy Dart applications"
 script: |
-    cd $HOME
-
     # Install Dart SDK
     wget "https://storage.googleapis.com/dart-editor-archive-integration/latest/dartsdk-linux-64.tar.gz"
     tar zvxf  dartsdk-linux-64.tar.gz
 
     # Assert dart_sdk directory
-    test -d $HOME/dart_sdk || { echo "$(ls -a $HOME)" ; echo "dart_sdk directory not found at $HOME/dart_sdk, terminating."; exit 1; }
+    test -d $HOME/dart-sdk || { echo "$(ls -a $HOME)" ; echo "dart_sdk directory not found at $HOME/dart_sdk, terminating."; exit 1; }
 
     # Write environment variables
-    echo 'export DART_SDK="$HOME/dart_sdk' >> $HOME/.bash_profile
+    echo 'export DART_SDK="$HOME/dart-sdk' >> $HOME/.bash_profile
     echo 'export PATH="$PATH:$DART_SDK/bin' >> $HOME/.bash_profile
 
     # Update environment variables
